"""baseline full analytics schema

Revision ID: c8257193f253
Revises: 
Create Date: 2025-11-19 11:20:24.115204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c8257193f253'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_execution_status',
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('scheduler_name', sa.String(length=100), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('db_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('execution_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('crm_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('execution_id', name='scheduler_execution_status_pkey'),
    sa.UniqueConstraint('scheduler_name', 'batch_id', 'db_name', name='unique_scheduler_batch_db'),
    schema='public'
    )
    op.create_index('idx_scheduler_status_batch', 'scheduler_execution_status', ['batch_id', 'scheduler_name'], unique=False, schema='public')
    op.create_index('idx_scheduler_status_cleanup', 'scheduler_execution_status', ['start_time'], unique=False, schema='public')
    op.create_index('idx_scheduler_status_lookup', 'scheduler_execution_status', ['scheduler_name', 'status', 'start_time'], unique=False, schema='public')
    op.create_index('idx_scheduler_status_recent', 'scheduler_execution_status', ['scheduler_name', 'db_name', 'start_time'], unique=False, schema='public')
    op.create_table('user_profiles',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('db_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('has_real_email', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('email', name='user_profiles_pkey'),
    sa.UniqueConstraint('username', name='user_profiles_username_key'),
    schema='public'
    )
    op.create_index('idx_user_profiles_username', 'user_profiles', ['username'], unique=False, schema='public')
    op.create_index('ix_user_profiles_email', 'user_profiles', ['email'], unique=False, schema='public')
    op.create_table('daily_usage_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('total_time_spent_ms', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens_used', sa.BigInteger(), nullable=True),
    sa.Column('modules_accessed', sa.JSON(), nullable=True),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('total_clicks', sa.Integer(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('total_api_calls', sa.Integer(), nullable=True),
    sa.Column('avg_session_duration_ms', sa.Double(precision=53), nullable=True),
    sa.Column('error_rate', sa.Double(precision=53), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['public.user_profiles.email'], name='daily_usage_reports_user_email_fkey'),
    sa.PrimaryKeyConstraint('id', name='daily_usage_reports_pkey'),
    schema='public'
    )
    op.create_index('ix_daily_usage_reports_report_date', 'daily_usage_reports', ['report_date'], unique=False, schema='public')
    op.create_index('ix_daily_usage_reports_user_email', 'daily_usage_reports', ['user_email'], unique=False, schema='public')
    op.create_table('module_usage_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=True),
    sa.Column('total_visits', sa.Integer(), nullable=True),
    sa.Column('total_time_spent_ms', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens_used', sa.BigInteger(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('daily_visits', sa.JSON(), nullable=True),
    sa.Column('weekly_summary', sa.JSON(), nullable=True),
    sa.Column('monthly_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['public.user_profiles.email'], name='module_usage_summary_user_email_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='module_usage_summary_pkey'),
    schema='public'
    )
    op.create_index('ix_module_usage_summary_module_name', 'module_usage_summary', ['module_name'], unique=False, schema='public')
    op.create_index('ix_module_usage_summary_user_email', 'module_usage_summary', ['user_email'], unique=False, schema='public')
    op.create_table('user_activity_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_name', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('action_category', sa.String(length=100), nullable=True),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('action_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_status', sa.String(length=50), server_default=sa.text("'success'::character varying"), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.CheckConstraint("action_type::text = ANY (ARRAY['authentication'::character varying, 'navigation'::character varying, 'chat'::character varying, 'crm'::character varying, 'lead_generation'::character varying, 'analytics'::character varying, 'task_management'::character varying, 'calendar'::character varying, 'settings'::character varying, 'upload'::character varying, 'export'::character varying]::text[])", name='valid_action_type'),
    sa.CheckConstraint("result_status::text = ANY (ARRAY['success'::character varying, 'error'::character varying, 'pending'::character varying, 'timeout'::character varying]::text[])", name='valid_result_status'),
    sa.ForeignKeyConstraint(['user_email'], ['public.user_profiles.email'], name='fk_user_activity_logs_user_email', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_activity_logs_pkey'),
    schema='public'
    )
    op.create_index('idx_user_activity_logs_action_data', 'user_activity_logs', ['action_data'], unique=False, schema='public')
    op.create_index('idx_user_activity_logs_action_type', 'user_activity_logs', ['action_type'], unique=False, schema='public')
    op.create_index('idx_user_activity_logs_session', 'user_activity_logs', ['session_id'], unique=False, schema='public')
    op.create_index('idx_user_activity_logs_tags', 'user_activity_logs', ['tags'], unique=False, schema='public')
    op.create_index('idx_user_activity_logs_user_timestamp', 'user_activity_logs', ['user_email', 'timestamp'], unique=False, schema='public')
    op.create_table('user_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('session_start', sa.DateTime(), nullable=True),
    sa.Column('session_end', sa.DateTime(), nullable=True),
    sa.Column('session_duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('module_name', sa.String(length=255), nullable=True),
    sa.Column('module_visits', sa.Integer(), nullable=True),
    sa.Column('module_time_spent_ms', sa.BigInteger(), nullable=True),
    sa.Column('tokens_used', sa.BigInteger(), nullable=True),
    sa.Column('token_cost_estimate', sa.Double(precision=53), nullable=True),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('actions_performed', sa.JSON(), nullable=True),
    sa.Column('clicks_count', sa.Integer(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=True),
    sa.Column('files_uploaded', sa.Integer(), nullable=True),
    sa.Column('api_calls_made', sa.Integer(), nullable=True),
    sa.Column('avg_response_time_ms', sa.Double(precision=53), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('browser', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['public.user_profiles.email'], name='user_analytics_user_email_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_analytics_pkey'),
    schema='public'
    )
    op.create_index('ix_user_analytics_created_at', 'user_analytics', ['created_at'], unique=False, schema='public')
    op.create_index('ix_user_analytics_module_name', 'user_analytics', ['module_name'], unique=False, schema='public')
    op.create_index('ix_user_analytics_session_id', 'user_analytics', ['session_id'], unique=False, schema='public')
    op.create_index('ix_user_analytics_user_email', 'user_analytics', ['user_email'], unique=False, schema='public')
    op.create_table('user_session_summaries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('session_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_actions', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('pages_visited', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('services_used', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('chat_messages_sent', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('crm_interactions', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('leads_generated', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('analytics_queries', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('ai_tools_used', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('total_ai_thinking_time_ms', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('average_response_time_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('errors_encountered', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('session_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_accomplishments', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['public.user_profiles.email'], name='fk_user_session_summaries_user_email', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_session_summaries_pkey'),
    sa.UniqueConstraint('user_email', 'session_id', name='user_session_summaries_user_email_session_id_key'),
    schema='public'
    )
    op.create_index('idx_user_session_summaries_session_id', 'user_session_summaries', ['session_id'], unique=False, schema='public')
    op.create_index('idx_user_session_summaries_summary', 'user_session_summaries', ['session_summary'], unique=False, schema='public')
    op.create_index('idx_user_session_summaries_user_start', 'user_session_summaries', ['user_email', 'session_start'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_session_summaries_user_start', table_name='user_session_summaries', schema='public')
    op.drop_index('idx_user_session_summaries_summary', table_name='user_session_summaries', schema='public')
    op.drop_index('idx_user_session_summaries_session_id', table_name='user_session_summaries', schema='public')
    op.drop_table('user_session_summaries', schema='public')
    op.drop_index('ix_user_analytics_user_email', table_name='user_analytics', schema='public')
    op.drop_index('ix_user_analytics_session_id', table_name='user_analytics', schema='public')
    op.drop_index('ix_user_analytics_module_name', table_name='user_analytics', schema='public')
    op.drop_index('ix_user_analytics_created_at', table_name='user_analytics', schema='public')
    op.drop_table('user_analytics', schema='public')
    op.drop_index('idx_user_activity_logs_user_timestamp', table_name='user_activity_logs', schema='public')
    op.drop_index('idx_user_activity_logs_tags', table_name='user_activity_logs', schema='public')
    op.drop_index('idx_user_activity_logs_session', table_name='user_activity_logs', schema='public')
    op.drop_index('idx_user_activity_logs_action_type', table_name='user_activity_logs', schema='public')
    op.drop_index('idx_user_activity_logs_action_data', table_name='user_activity_logs', schema='public')
    op.drop_table('user_activity_logs', schema='public')
    op.drop_index('ix_module_usage_summary_user_email', table_name='module_usage_summary', schema='public')
    op.drop_index('ix_module_usage_summary_module_name', table_name='module_usage_summary', schema='public')
    op.drop_table('module_usage_summary', schema='public')
    op.drop_index('ix_daily_usage_reports_user_email', table_name='daily_usage_reports', schema='public')
    op.drop_index('ix_daily_usage_reports_report_date', table_name='daily_usage_reports', schema='public')
    op.drop_table('daily_usage_reports', schema='public')
    op.drop_index('ix_user_profiles_email', table_name='user_profiles', schema='public')
    op.drop_index('idx_user_profiles_username', table_name='user_profiles', schema='public')
    op.drop_table('user_profiles', schema='public')
    op.drop_index('idx_scheduler_status_recent', table_name='scheduler_execution_status', schema='public')
    op.drop_index('idx_scheduler_status_lookup', table_name='scheduler_execution_status', schema='public')
    op.drop_index('idx_scheduler_status_cleanup', table_name='scheduler_execution_status', schema='public')
    op.drop_index('idx_scheduler_status_batch', table_name='scheduler_execution_status', schema='public')
    op.drop_table('scheduler_execution_status', schema='public')
    # ### end Alembic commands ###
